name: Continuous Deployment
on:
    push:
        branches:
            - main
jobs:
    AWS-CDK:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: cdk diff
              run: |
                  AWS_PROFILE={{AWS_PROFILE}} \
                  AWS_ACCOUNT_ID=$(just get-aws-account-id) \
                  CDK_DEFAULT_REGION={{AWS_REGION}} \
                  AWS_REGION={{AWS_REGION}} \
                  cdk diff \
                      --profile {{AWS_PROFILE}} \
                      --region {{AWS_REGION}} \
                      --app "python3 app.py"

            - name: cdk deploy
              run: |
                  AWS_PROFILE={{AWS_PROFILE}} \
                  CDK_DEFAULT_REGION={{AWS_REGION}} \
                  AWS_REGION={{AWS_REGION}} \
                  cdk deploy \
                      --all \
                      --diff \
                      --require-approval never \
                      --profile {{AWS_PROFILE}} \
                      --region {{AWS_REGION}} \
                      --app "python app.py"
